### ISSUE TITLE
Could not download kotlin-serialization-1.6.10.jar in Xcode

### ISSUE THREAD

**Issue by ruzhuxiaogu** [joreilly/PeopleInSpace#119]
* What went wrong:
A problem occurred configuring root project 'PeopleInSpace'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not download kotlin-serialization-1.6.10.jar (org.jetbrains.kotlin:kotlin-serialization:1.6.10)
      > Could not get resource 'https://repo.maven.apache.org/maven2/org/jetbrains/kotlin/kotlin-serialization/1.6.10/kotlin-serialization-1.6.10.jar'.
         > Could not GET 'https://repo.maven.apache.org/maven2/org/jetbrains/kotlin/kotlin-serialization/1.6.10/kotlin-serialization-1.6.10.jar'.
            > Unsupported or unrecognized SSL message

anyone can help me?

**Comment by joreilly** [comment]
Are you still seeing this?
