### ISSUE TITLE
Add Open-source License?

### ISSUE THREAD

**Issue by fkistner** [joreilly/PeopleInSpace#13]
Hi,

cool little project! Kudos!
I was wondering whether you had considered open-sourcing this under a permissive Open-Source License, such as MIT or Apache?
I could see this being a nice starting point similar to KaMPKit for many projects.

Cheers,
Florian

**Comment by joreilly** [comment]
Hi @fkistner , I hadn't thought there was anything preventing it from being used like that right now (and is linked for example from official KMM docs - https://kotlinlang.org/docs/mobile/samples.html#peopleinspace).  I can certainly add one though if it makes it easier....I see that KaMPKit uses Apache-2.0 so I guess can use that

**Comment by joreilly** [comment]
done!
