### ISSUE TITLE
Usage of compose-ios

### ISSUE THREAD

**Issue by alandoni** [joreilly/PeopleInSpace#137]
Hi, can you help me? where can I find documentation or tutorials for compose-ios?

I tried to run  ./gradlew compose-ios:iosDeployIPhone8Debug

but it threw the following error:

> Field 'dataPathSize' is required for type with serial name 'org.jetbrains.compose.experimental.uikit.internal.DeviceData', but it was missing

**Comment by joreilly** [comment]
Hi, 

Compose for iOS is at every experimental stage right now I believe.  There was some discussion in following if it helps but I'm not surprised there's still issues.  Could perhaps be related to XCode version for example installed.  I'd suggest perhaps asking in kotlinlang slack "compose-ios" channel .

https://github.com/joreilly/PeopleInSpace/pull/127

**Comment by joreilly** [comment]
Also worth perhaps trying out JetBrains sample https://github.com/JetBrains/compose-jb/tree/master/experimental/examples/falling-balls-mpp

**Comment by joreilly** [comment]
I'm actually seeing issues here with the JetBrains samples and also PeopleInSpace.....suspecting it might be related to XCode update I did here recently....though getting different error here I think

```
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Unable to boot device because we cannot determine the runtime bundle.
```

**Comment by alandoni** [comment]
I was trying to find more informations about compose for ios but I couldn't, I know it's experimental but I just want to try and understand it

sadly my macbook is old and I can't update it anymore, hope it work with the latest version of big sur :( 

thank you, your project is helping me a lot in my studies and curiosity!

**Comment by alandoni** [comment]
I tried in another macbook, with a newer version of xcode, it only changed the error, but still unable to compile :(

**Comment by TaehoonLeee** [comment]
Would you like to change the Jetbrains compose version? 

I'm not sure which version it is.

**Comment by alandoni** [comment]
I'm using 1.2.0-alpha01-dev683, the same the project uses

```
kotlinVersion=1.6.21
sqlDelightVersion=1.5.3
koinVersion=3.2.0
ktorVersion=2.0.1
composeVersion=1.2.0-beta01
composePluginVersion=1.2.0-alpha01-dev683
coroutinesVersion=1.6.1
```

**Comment by TaehoonLeee** [comment]
I'm sorry. I was mistaken because I used a different MacBook.

I also had an error that looked like a version issue? on some MacBooks. I will share it when I solve it.

**Comment by TaehoonLeee** [comment]
@alandoni I solve the issue by adding below code in gradle.properties

> kotlin.native.cacheKind=none

**Comment by joreilly** [comment]
fyi that I also just opened following PR to update compose ios version and also to switch to different simulator (had issues with iphone 8 here for some reason after updating to latest XCode) https://github.com/joreilly/PeopleInSpace/pull/141

**Comment by joreilly** [comment]
btw also seems to be working here without `kotlin.native.cacheKind=none` (running on M1 laptop)

**Comment by alandoni** [comment]
Thanks for the gelo, using that line in gradle.properties did the trick for
me, I still need to check the changelog of compose, EditText is not working
yet :(

Em ter., 14 de jun. de 2022 00:03, joreilly ***@***.***>
escreveu:
