### ISSUE TITLE
[Question] PersonDetailsRoute > uiState line triggers multiple times

### ISSUE THREAD

**Issue by Drjacky** [joreilly/PeopleInSpace#159]
Any idea why this line triggers a couple of times?
https://github.com/joreilly/PeopleInSpace/blob/93955919ee4c8b3bfe0118680961b1e153a0b765/app/src/main/java/com/surrus/peopleinspace/persondetails/PersonDetailsScreen.kt#L39

**Comment by joreilly** [comment]
By this do you mean that recomposition occurs more often than you think it should?

**Comment by joreilly** [comment]
That state will be initially Loading and then should transition, if not errors, to having the result.

**Comment by Drjacky** [comment]
Yes, if you put a breakpoint on that line, it triggers more than once or twice.
But in the log, I couldn't see the API called more than once! [which is good]
