### ISSUE TITLE
Add CLI example for macOS

### ISSUE THREAD

**Issue by mreichelt** [joreilly/PeopleInSpace#16]
Hey there @joreilly!

Thank you for this awesome project! 🌟

What do you think about minimal CLI examples (Kotlin native binaries) - for showing the ISS position and astronauts in space? Examples:

```console
$ ./people_in_space astronauts
Loading astronauts from space...
Kate Rubins
Mike Hopkins
Sergey Kud-Sverchkov
Sergey Ryzhikov
Shannon Walker
Soichi Noguchi
Victor Glover
```

Similarly, the ISS position could be shown using `./people_in_space iss`, and `./people_in_space` would show a help with options.

Would you like an open source contribution in this direction, a CLI example for mac (and Linux/Windows later)? I think it could help people getting started with Kotlin Native for CLI applications.

**Comment by joreilly** [comment]
Absolutely, sounds like a really nice idea!

**Comment by mreichelt** [comment]
Awesome! I'll gladly contribute this :)

**Comment by joreilly** [comment]
Hi @mreichelt, I'm just scanning through open issues here and wondering if this is something you're still hoping to add?
