### ISSUE TITLE
Update Kotlin to `1.7.20`

### ISSUE THREAD

**Issue by YektaDev** [joreilly/PeopleInSpace#168]
The Kotlin 1.7.20 release [is out](https://blog.jetbrains.com/kotlin/2022/09/kotlin-1-7-20-released/)!

**Comment by YektaDev** [comment]
An update: [Compose compiler 1.3.2](https://developer.android.com/jetpack/androidx/releases/compose-compiler#1.3.2) is updated to Kotlin 1.7.20

**Comment by joreilly** [comment]
Still blocked right now on Compose for Web version that supports 1.7.20

**Comment by YektaDev** [comment]
✅ #174
