### ISSUE TITLE
how to build the ios app

### ISSUE THREAD

**Issue by TheReprator** [joreilly/PeopleInSpace#184]
As when i try to open .xcodeworspace, it say KoinKt not found

**Comment by joreilly** [comment]
When you open up first it's probably going to say that as framework for shared code hasn't been built yet.  What happens when you try to run/build project in XCode?

**Comment by TheReprator** [comment]
@joreilly  First thanks for the quick response. I can't explain much, so hereby i am attaching the image, hope it helps to analyze the issue.
<img width="1414" alt="Screenshot 2022-12-23 at 11 03 07 PM" src="https://user-images.githubusercontent.com/10286587/209395107-c156bd33-1ba2-44fa-9331-ac419d6e1df8.png">

**Comment by TheReprator** [comment]
Screen Recording 2022-12-23 at 11.00.43 PM.mov
<https://drive.google.com/file/d/1y554NqaFzsD3iXj501xDjse6ojVkQXh1/view?usp=drive_web>

First thanks for the quick response. I can't explain much, so hereby i am
attaching the video, hope it helps to analyze the issue.
