### ISSUE TITLE
macOS example runs fine on macOS 10.15 - but is enabled for >=10.16

### ISSUE THREAD

**Issue by mreichelt** [joreilly/PeopleInSpace#20]
I had to downgrade the `Deployment target`  of my macOS build to `10.15` (because I didn't upgrade yet) - and it seems to run smoothly.

If possible, I would like to set the deployment target to 10.15.

**Comment by joreilly** [comment]
Yeah, that should be fine.....don't think I had any particular reason to set it to what it was.
