### ISSUE TITLE
Upgrading to Android Studio Arctic Fox Canary 3 breaks Gradle build

### ISSUE THREAD

**Issue by mreichelt** [joreilly/PeopleInSpace#23]
Android Studio Arctic Fox Canary 2 works fine - but upgrading to Canary 3 (and upgrading Gradle to 6.8-rc1 and android plugin to 7.0.0-alpha03 breaks the build:

```console
➜  PeopleInSpace git:(master) ✗ ./gradlew assemble                         

> Configure project :backend

The 'org.jetbrains.kotlin.platform.*' plugins are deprecated and will no longer be available in Kotlin 1.4.
Please migrate the project to the 'org.jetbrains.kotlin.multiplatform' plugin.
See: https://kotlinlang.org/docs/reference/building-mpp-with-gradle.html

> Configure project :common
To take advantage of the new functionality for Cocoapods Integration like synchronizing with the Xcode project 
and supporting dependencies on pods, please install the `cocoapods-generate` plugin for CocoaPods 
by calling `gem install cocoapods-generate` in terminal. 

More details are available by https://github.com/square/cocoapods-generate

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':common'.
> Configuration with name 'testApi' not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.8-rc-1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 735ms
```

**Comment by mreichelt** [comment]
I tried to find `testApi`, but it seems that is not used by the gradle files of PeopeInSpace. Maybe by some plugin that is used?

**Comment by mreichelt** [comment]
Resetting the gradle files to before the upgrade gets `./gradlew assemble` running - still investigating.
Next up, I'll try to upgrade Gradle to 6.8-rc1 and see if the build works.

**Comment by mreichelt** [comment]
Upgrading to 6.8-rc1 seems to work fine - I added the line 

```
distributionUrl=https://services.gradle.org/distributions/gradle-6.8-rc-1-bin.zip
```

to `gradle-wrapper.properties`, and it still compiles.

**Comment by joreilly** [comment]
seems to be related to https://kotlinlang.slack.com/archives/C0B8M7BUY/p1607989735365000

which references https://issuetracker.google.com/issues/175496966

**Comment by mreichelt** [comment]
Hmm, so the only option right now would be to roll back to Android Studio Arctic Fox Canary 2.

Or maybe we downgrade the project again to a more stable Android Studio release? What was the reason to use 4.3 in the first place, in contrast to the more stable 4.2?

**Comment by mreichelt** [comment]
Downgrading to Canary 2 for now.

**Comment by Solidogen** [comment]
@mreichelt Compose works only on canary builds
