### ISSUE TITLE
Watch App preventing successful builds

### ISSUE THREAD

**Issue by RyPope** [joreilly/PeopleInSpace#263]
```
Showing All Issues
> Task :common:embedAndSignAppleFrameworkForXcode FAILED



FAILURE: Build failed with an exception.



* What went wrong:

Some problems were found with the configuration of task ':common:embedAndSignAppleFrameworkForXcode' (type 'FrameworkCopy').

  - In plugin 'org.jetbrains.kotlin.gradle.scripting.internal.ScriptingKotlinGradleSubplugin' type 'org.jetbrains.kotlin.gradle.plugin.mpp.apple.FrameworkCopy' property 'destinationDirectory' doesn't have a configured value.

    

    Reason: This property isn't marked as optional and no value has been configured.

    

    Possible solutions:

      1. Assign a value to 'destinationDirectory'.

      2. Mark property 'destinationDirectory' as optional.

    

    For more information, please refer to https://docs.gradle.org/8.4/userguide/validation_problems.html#value_not_set in the Gradle documentation.

  - In plugin 'org.jetbrains.kotlin.gradle.scripting.internal.ScriptingKotlinGradleSubplugin' type 'org.jetbrains.kotlin.gradle.plugin.mpp.apple.FrameworkCopy' property 'sourceFramework' doesn't have a configured value.

    

    Reason: This property isn't marked as optional and no value has been configured.

    

    Possible solutions:

      1. Assign a value to 'sourceFramework'.

      2. Mark property 'sourceFramework' as optional.

    

    For more information, please refer to https://docs.gradle.org/8.4/userguide/validation_problems.html#value_not_set in the Gradle documentation.



* Try:

> Run with --stacktrace option to get the stack trace.

> Run with --info or --debug option to get more log output.

> Run with --scan to get full insights.

> Get more help at https://help.gradle.org.



Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.



You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.



For more on this, please refer to https://docs.gradle.org/8.4/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.



BUILD FAILED in 17s

4 actionable tasks: 1 executed, 3 up-to-date

Some problems were found with the configuration of task ':common:embedAndSignAppleFrameworkForXcode' (type 'FrameworkCopy').
```

This happens when trying to install on a physical iPhone 12 Pro. I don't encounter this when trying to install on a simulator so I think it's an architecture issue, but I've been unable to resolve it on my own by messing around with build options.

**Comment by joreilly** [comment]
Hmm, not sure what cause of that is...I've reproduced also by trying to archive.  It must be a regression as I have previously tried to publish to app store (but was rejected ;) )

**Comment by joreilly** [comment]
also asked here https://kotlinlang.slack.com/archives/C3PQML5NU/p1698171088996439

**Comment by joreilly** [comment]
seems to be somehow related to this commit https://github.com/joreilly/PeopleInSpace/commit/f5804031a584a359eee3a637ca732c547b93c05d . So, been broken for a while it seems.....need to add something to GH workflow to check that  once resolved

**Comment by joreilly** [comment]
hmm, I think that's separate issue related to use of Xcode 15....related to https://youtrack.jetbrains.com/issue/KT-60230/Native-unknown-options-iossimulatorversionmin-sdkversion-with-Xcode-15-beta-3

**Comment by joreilly** [comment]
Definitely seems to be watchos related....if you remove watch target in Xcode then it builds fine.....think it's related to architectures being used.....possibly related to following but not certain https://youtrack.jetbrains.com/issue/KT-53107/Add-arm64-support-for-watchOS-targets-Xcode-14

**Comment by joreilly** [comment]
I've just merged https://github.com/joreilly/PeopleInSpace/pull/265 which appears to address this....not certain it will run on physical watchos device as don't have one to test on but should at least not block doing archive build etc.  @RyPope can you try again with latest code?

**Comment by RyPope** [comment]
@joreilly back in business! thanks for digging into that
