### ISSUE TITLE
This version of the Android Support plugin for IntelliJ IDEA (or Android Studio) cannot open this project, please retry with version 4.3 or newer.

### ISSUE THREAD

**Issue by RdeWilde** [joreilly/PeopleInSpace#31]
First of all, I appreciate the efforts to publish this project and all the articles around it, really awesome.

Secondly, when building the project, I get this error:

`This version of the Android Support plugin for IntelliJ IDEA (or Android Studio) cannot open this project, please retry with version 4.3 or newer.`

I use the 7.0.0-alpha4 plugin (Intellij IDEA CE), so it should work imho. Any clue how to resolve this?

**Comment by RdeWilde** [comment]
Probably related: https://youtrack.jetbrains.com/issue/IDEA-252823

**Comment by RdeWilde** [comment]
```
Unfortunately, IDEA does not support AGP 4.1 yet. You have two options: either downgrade AGP and use IDEA:
- com.android.tools.build:gradle:4.0.2
- or switch to Android Studio 4.1+.
```

**Comment by joreilly** [comment]
Are you using Canary version of Android Studio?

**Comment by RdeWilde** [comment]
I was using Intellij IDEA, but now I switched to Android Studio Canary release, and it works :-)

**Comment by CMingTseng** [comment]
About this  ( Jetpack Compose)

can  apply  this  gradle

https://github.com/CKS-ROC/Useful_Gradle/blob/master/config_preuse_compose.gradle

apply from: 'https://raw.githubusercontent.com/CKS-ROC/Useful_Gradle/master/config_preuse_compose.gradle'

THX
