### ISSUE TITLE
Question about project template

### ISSUE THREAD

**Issue by franconob** [joreilly/PeopleInSpace#33]
Hello there. First of all, awesome project, very complete! I want to ask you if you were able to create the KMM project using the project wizard, because I don't see the option to choose KMM with the latest Canary 6. If not, which template did you chose?

Thanks!

**Comment by joreilly** [comment]
Hi @franconob , this project was created before the KMM plugin existed so was more or less done from scratch.  Regarding that plugin and Canary 6, I believe there are known issues right now....hopefully something that will get resolved soon.

**Comment by franconob** [comment]
Great, thanks for the reply!
