### ISSUE TITLE
How to run backend locally

### ISSUE THREAD

**Issue by RafaO** [joreilly/PeopleInSpace#43]
Hi! Thanks for sharing this, I quite like the project and was trying to replicate it by adding a backend server in one of my projects. Unfortunately, I am struggling a bit because the jvm code is not able to use the sharedCommon files.

I started playing around with your project and as a suggestion, I think it would helpful if you added to the readme the instructions to run the backend server locally in case that's possible.

Thanks again.

**Comment by joreilly** [comment]
Hmm, haven't actually run this in a while and getting some netty errors now when I run that (using either `./gradlew :backend:run` or running `Server.kt` directly within Android Studio).  Were you able to successfully run there?

**Comment by joreilly** [comment]
Good point, will update shortlyl
