### ISSUE TITLE
 java.lang.NoSuchMethodError: No virtual method elapsedNow-UwyO8pc()D in class Lkotlin/time/TimeMark; or its super classes (declaration of 'kotlin.time.TimeMark' appears in /data/app/com.surrus.peopleinspace-kswk9z_v3x_aBC69JDlTfg==/base.apk!classes3.dex)

### ISSUE THREAD

**Issue by CMingTseng** [joreilly/PeopleInSpace#45]
Dear Sir

i get this crash 

 java.lang.NoSuchMethodError: No virtual method elapsedNow-UwyO8pc()D in class Lkotlin/time/TimeMark; or its super classes (declaration of 'kotlin.time.TimeMark' appears in /data/app/com.surrus.peopleinspace-kswk9z_v3x_aBC69JDlTfg==/base.apk!classes3.dex)
 
 like this  https://github.com/InsertKoinIO/koin/issues/871
 
 THX

**Comment by joreilly** [comment]
Can you tell me anything about your environment that would help reproduce?

**Comment by CMingTseng** [comment]
Dear Sir

this issue can close !!

i clean project  .idea & .gradle   &  gradle cache & build 

now it work !!

THX
