### ISSUE TITLE
PeopleInSpace @web  can use  "Compose for Desktop " ?

### ISSUE THREAD

**Issue by CMingTseng** [joreilly/PeopleInSpace#46]
Dear Sir

this project   https://github.com/JetBrains/compose-for-web-demos  &　this https://github.com/ShikaSD/compose-browser-demo  &  this  https://github.com/ShikaSD/compose-server-side

Demo "Compose for Desktop" at Web 

can teach me or demo  at this project ?

THX

**Comment by joreilly** [comment]
This isn't something I'm that familiar with but will probably look at incorporating when it becomes more mature.

**Comment by CMingTseng** [comment]
Dear Sir

i look the last demo 

https://github.com/JetBrains/compose-jb/tree/master/examples/todoapp/web

now todo app  have web version ??!!

but i try build it fail --> get lost  "NodeJsRootExtension"

can you fix it ? 

and modify  your PeopleInSpace use  kotlin multiplatform ?

THX
