### ISSUE TITLE
Compose in shared android code?

### ISSUE THREAD

**Issue by cyberhenoch** [joreilly/PeopleInSpace#48]
Hi
thanks for publishing this. It is good for picking up good practices in multiplatform project.

I am wondering if we can have compose code in shared part (/common/src/androidMain) or just in the platform code (app/src/main). 
I have created a [SO question](https://stackoverflow.com/questions/67472281/shared-activity-with-compose-in-kotlin-multiplatform-project) with some project setup as an example but no luck as far :(
Am I missing something?

**Comment by joreilly** [comment]
Yes, I believe this is possible and in fact one of the IntelliJ options when creating new project is to create such a project. It's not something I've tried so far but hopefully will at some point soon.

**Comment by cyberhenoch** [comment]
Thanks for the hint. I've just installed IntelliJ IDEA and the Kotlin/Multiplatform/Mobile Application option is there. But even with the compose plugin installed I can't see any compose-related options there. I manually set up the shared activity with compose in this template but still have the same error at runtime:

`No static method setContent$default(Landroidx/activity/ComponentActivity;Landroidx/compose/runtime/CompositionContext;`

**Comment by joreilly** [comment]
This is the one I was thinking of.

<img width="381" alt="Screenshot 2021-05-12 at 17 10 35" src="https://user-images.githubusercontent.com/6302/118008517-0c92e180-b345-11eb-855b-08d79481b41d.png">

**Comment by cyberhenoch** [comment]
You are right - this one has compose and I managed to add & run compose code from the common part after creating it from this wizard. Now I'll try to find out what is the key difference. Thank you for your help!

**Comment by cyberhenoch** [comment]
Adding **org.jetbrains.compose** plugin fixed it, more details [here](https://stackoverflow.com/questions/67472281/shared-activity-with-compose-in-kotlin-multiplatform-project)
Thanks again :)
