### ISSUE TITLE
Webpack 5+ has no more polyfills

### ISSUE THREAD

**Issue by RdeWilde** [joreilly/PeopleInSpace#49]
It'll produce an error about 'crypto' not being available, and that Webpack 5 no longer supplies polyfills out of the box, but you have explicit enable or disable it.

This is the example I used to add it, but I guesst here are more ways:
https://github.com/juggernaut0/multiplatform-utils/blob/cbacca8abf26a8ff946736c01510222090dcc74f/ktor/build.gradle.kts#L49

Background info https://stackoverflow.com/questions/54162297/module-not-found-error-cant-resolve-crypto/54162447

```
> Task :common:jsBrowserProductionWebpack
Module not found: Error: Can't resolve 'crypto' in '/Users/me/projects/some/build/js/packages/some-common/kotlin-dce'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "crypto": require.resolve("crypto-browserify") }'
	- install 'crypto-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "crypto": false }
```

But I don't know how to implement the resolve...?

**Comment by RdeWilde** [comment]
Found this: https://youtrack.jetbrains.com/issue/KT-46082

**Comment by joreilly** [comment]
@RdeWilde I can add that workaround here as part of updates to use Kotlin 1.5.0 (once Compose version is available, hopefully soon, that supports 1.5)

**Comment by joreilly** [comment]
@RdeWilde actually, just to confirm....are you seeing this on versions earlier that Kotlin 1.5?

**Comment by RdeWilde** [comment]
> @RdeWilde actually, just to confirm....are you seeing this on versions earlier that Kotlin 1.5?

No, I haven't

**Comment by hfhbd** [comment]
After updating to Ktor client 1.6.0, this error is fixed and the workaround is not longer required.

**Comment by joreilly** [comment]
Sounds like this issue is resolved so closing....feel free to re-open if that's not the case.
