### ISSUE TITLE
Can not run on simulator on Apple M1 MacBook

### ISSUE THREAD

**Issue by StefanOltmann** [joreilly/PeopleInSpace#50]
The XCode project seems to be hardcoded to be build for Intel architecture.
I need documentation what needs to be changed to get it running.
A branch with the changes might be useful.

**Comment by joreilly** [comment]
I don't have M1 to test this but PRs are always welcome if you are aware of what the changes are...or at least as you say some added documentation.

**Comment by joreilly** [comment]
@StefanOltmann can you check this with latest version....there's been a few version updates (e.g. gradle plugin) that perhaps will affect this.

**Comment by StefanOltmann** [comment]
I investigated here a bit:

It works if started with the KMM Android Studio Plugin. They hacked it somehow to get it working.

Started from XCode it fails because arm64 is not built for simulator and x86 must be included for Kotlin Native.

This is all pretty messed up, but I saw that there is a fix with upcoming Kotlin 1.5.30-M1

So there is nothing you and I can do about it. I tried. 😉

Issue closed.

**Comment by joreilly** [comment]
Hmm, interesting....I wonder what KMM plugin is doing to allow that.

**Comment by StefanOltmann** [comment]
> Hmm, interesting....I wonder what KMM plugin is doing to allow that.

Yes, I would really like to know that. If this is a special configuration that could also be applied to the XCode project that would help a lot of people.

For now I guess they hacked something in it that will get a proper and official support in 1.5.30
