### ISSUE TITLE
Gradle sync fails with latest stable Andriod Sudio + KMM plugin

### ISSUE THREAD

**Issue by ktchernov** [joreilly/PeopleInSpace#56]
AS 4.2.1 / KMM plugin v0.2.6

Clean check out of PeopleInSpace, Gradle sync fails with:

Unrecognized Android Studio (or Android Support plugin for IntelliJ IDEA) version '202.7660.26.42.7351085', please retry with version 2020.3.1 or newer.

**Comment by joreilly** [comment]
Android Studio Arctic Fox is minimum version required.....due to use of Jetpack Compose.

**Comment by hfhbd** [comment]
You could downgrade to AGP 4.2.1, but you will miss all IDE tooling, like the live previews.

**Comment by NorbertSandor** [comment]
Maybe not related but command line build fails as well:

>       > Could not resolve org.jetbrains:kotlin-react-router-dom:5.1.2-pre.110-kotlin-1.4.0.
>          > Could not get resource 'https://kotlin.bintray.com/kotlin-js-wrappers/org/jetbrains/kotlin-react-router-dom/5.1.2-pre.110-kotlin-1.4.0/kotlin-react-router-dom-5.1.2-pre.110-kotlin-1.4.0.pom'.
>             > Could not GET 'https://kotlin.bintray.com/kotlin-js-wrappers/org/jetbrains/kotlin-react-router-dom/5.1.2-pre.110-kotlin-1.4.0/kotlin-react-router-dom-5.1.2-pre.110-kotlin-1.4.0.pom'. Received status code 403 from server: Forbidden

**Comment by hfhbd** [comment]
@NorbertSandor Bintray is dead. Please use the mavenCentral published versions of `kotlin-js-wrappers`.

**Comment by NorbertSandor** [comment]
> @NorbertSandor Bintray is dead. Please use the mavenCentral published versions of `kotlin-js-wrappers`.

OK :)
But I was talking about this project's latest master version ;)

**Comment by joreilly** [comment]
That was actually updated recently https://github.com/joreilly/PeopleInSpace/commit/5109dba311cb82ae02454134edd007dcd9e9e68a

**Comment by hfhbd** [comment]
@joreilly Its is even published to mavenCentral, so you don't need the custom Space repo.

**Comment by joreilly** [comment]
Ah, great....thought I had seen issues when I omitted that repo but maybe something else not setup correctly.

**Comment by joreilly** [comment]
fyi that a recent commit actually broke the web clients (I really need to build out better test for those!).  Just pushed fix.  

For any other changes folks think make sense re. versions/dependencies etc then, as always, all PRs are welcome :)
