### ISSUE TITLE
The project is using an incompatible version (7.0.0-beta05) of the Android Gradle plugin.

### ISSUE THREAD

**Issue by RdeWilde** [joreilly/PeopleInSpace#64]
I'm experiencing this error when using Android Studio Arctic Fox 2020.3.1 RC1.

It seems like the error is about the Android Gradle plugin.

> The project is using an incompatible version (7.0.0-beta05) of the Android Gradle plugin.

It shows an option to start the upgrade assistant, but because the dependencies are as consts in the buildSrc, it isn't supported to do this automatically.

![Schermafbeelding 2021-07-21 om 21 32 00](https://user-images.githubusercontent.com/184016/126548856-63952ad8-7280-42a3-bd8e-8fccbbe2291b.png)

![Schermafbeelding 2021-07-21 om 21 32 53](https://user-images.githubusercontent.com/184016/126548873-0a20e376-7900-454a-ba7c-89f6f331f350.png)

Any clue how to resolve this?

**Comment by joreilly** [comment]
There was a recent PR that moved that in there but meant to actually move that particular dependency back to main `build.gradle.kts` for exactly this reason.  You can try that or also update it manually and resync.  Away for a few days but will also resync those across various projects when I get back.

**Comment by RdeWilde** [comment]
I changed the version for the gradle build tool to 7.0.0-rc01 (https://mvnrepository.com/artifact/com.android.tools.build/gradle/7.0.0-rc01) and I don't have the issue anymore atm.

https://github.com/joreilly/PeopleInSpace/blob/main/buildSrc/src/main/java/Dependencies.kt#L7

For Gradle I am (and was) using version 7.1.0 using the wrapper.

I'll report back if I would experience the issue again.

**Comment by joreilly** [comment]
Just pushed update to use 7.0.0-rc01.  I think we can close this now but feel free to re-open if not.
