### ISSUE TITLE
Plugin class 'org.jetbrains.kotlin.gradle.targets.js.nodejs.NodeJsRootPlugin': read system property 'idea.version'

### ISSUE THREAD

**Issue by RdeWilde** [joreilly/PeopleInSpace#65]
When my build succeeded, Android Studio gave me the option to 'optimize this' (from the 'Build analyzer'-tab), so I clicked it, which turned into an error:

> Configuration cache problems found in this build.
> 
> 1 problem was found storing the configuration cache.
> - Plugin class 'org.jetbrains.kotlin.gradle.targets.js.nodejs.NodeJsRootPlugin': read system property 'idea.version'
>   See https://docs.gradle.org/7.0.2/userguide/configuration_cache.html#config_cache:requirements:undeclared_sys_prop_read
> 
> See the complete report at file:///Users/Robert/projects/core/build/reports/configuration-cache/30jcug8vaoti1o1hwhkqheprb/configuration-cache-report.html
> > Read system property 'idea.version'

Not sure if this should be fixed from within this project, but at least I think it is good to login for reference.

I checked the documentation, but no clue how I could change it, as it seems to be about NodeJsRootPlugin.

![Schermafbeelding 2021-07-21 om 21 57 55](https://user-images.githubusercontent.com/184016/126552083-0b211bfe-d39c-4c7b-95e0-69575ed8008a.png)

A normal build succeeds fine.

**Comment by joreilly** [comment]
Is this still an issue?
