### ISSUE TITLE
Could not resolve io.ktor:ktor-client-js:1.6.3

### ISSUE THREAD

**Issue by CMingTseng** [joreilly/PeopleInSpace#72]
Dear Sir

i clone your latest modify 

when i build apk

get  "Could not resolve io.ktor:ktor-client-js:1.6.3"

THX

**Comment by joreilly** [comment]
This is an issue with ktor release publications (https://youtrack.jetbrains.com/issue/KTOR-3015)....you see that message when you sync but you can still run the application.  Though it seems from that issue that it should have been resolved in Kotlin 1.5.30 which I recently updated project to. Are you still seeing it if you do a gradle sync with latest code?
